### 채팅방 테스트

### 환경변수
@baseUrl = http://localhost:8080

@account = member-1
@password = password


# @no-cookie-jar
POST {{baseUrl}}/api/auth/token
Content-Type: application/json

{
  "memberId": "{{account}}",
  "password": "{{password}}"
}

> {%
    client.global.set("userToken", response.body.result.accessToken);
    client.log(`User Access Token: ${client.global.get("userToken")}`);
%}

