spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/standard_5h?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul}
    username: ${DB_USERNAME:standard}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  Kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        max.block.ms: 3000
        delivery.timeout.ms: 10000
        request.timeout.ms: 5000

kafka:
  inspection:
    group-id: ${INSPECTION_GROUP_ID:chat-inspection}
    listener-auto-start: ${INSPECTION_LISTENER_AUTO_START:true}

    ## 검사 실패 재현을 위한 설정 속성 값
    lab-enabled: true
    fault-event-id: ${INSPECTION_FAULT_EVENT_ID:}
    fault-point: ${INSPECTION_FAULT_POINT:BEFORE_PROCESS}
    fault-count: ${INSPECTION_FAULT_COUNT:0}

    ## 재발행할 메시지 ID 환경변수
    relay-message-id: ${INSPECTION_REPLAY_MESSAGE_ID}

security:
  jwt:
    issuer: live-commerce-standard
    access-token-ttl: 30m
    secret: ${APP_JWT_SECRET}